-- MySQL Script generated by MySQL Workbench
-- Tue Apr  7 13:52:03 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema LittleLemonDB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema LittleLemonDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `LittleLemonDB` DEFAULT CHARACTER SET utf8 ;
USE `LittleLemonDB` ;

-- -----------------------------------------------------
-- Table `LittleLemonDB`.`Menu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `LittleLemonDB`.`Menu` (
  `idMenu` INT NOT NULL,
  `plate_name` VARCHAR(200) NOT NULL,
  `price` FLOAT NOT NULL,
  `cuisine` VARCHAR(250) NOT NULL,
  `type` VARCHAR(250) NOT NULL,
  PRIMARY KEY (`idMenu`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `LittleLemonDB`.`CustomersNumber`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `LittleLemonDB`.`CustomersNumber` (
  `idCustomer_Number` INT NOT NULL AUTO_INCREMENT,
  `phone_1` VARCHAR(100) NOT NULL,
  `phone_2` VARCHAR(100) NULL,
  `fax` VARCHAR(100) NULL,
  `ingridients` VARCHAR(250) NULL,
  PRIMARY KEY (`idCustomer_Number`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `LittleLemonDB`.`CustomerDetails`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `LittleLemonDB`.`CustomerDetails` (
  `idCustomer` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(100) NULL,
  `last name` VARCHAR(100) NULL,
  `adress` VARCHAR(200) NULL,
  `isalergic` TINYINT NOT NULL,
  `date_of_registery` DATE NOT NULL,
  `birth_date` DATE NOT NULL,
  `phone_number` INT NULL,
  PRIMARY KEY (`idCustomer`),
  UNIQUE INDEX `first name_UNIQUE` (`first_name` ASC) VISIBLE,
  UNIQUE INDEX `last name_UNIQUE` (`last name` ASC) VISIBLE,
  UNIQUE INDEX `adress_UNIQUE` (`adress` ASC) VISIBLE,
  INDEX `customer_number_idx` (`phone_number` ASC) VISIBLE,
  CONSTRAINT `customer_number`
    FOREIGN KEY (`phone_number`)
    REFERENCES `LittleLemonDB`.`CustomersNumber` (`idCustomer_Number`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `LittleLemonDB`.`employees`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `LittleLemonDB`.`employees` (
  `idemployee` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NULL,
  `last_name` VARCHAR(45) NULL,
  `role` VARCHAR(45) NULL,
  `salary` VARCHAR(45) NULL,
  PRIMARY KEY (`idemployee`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `LittleLemonDB`.`Orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `LittleLemonDB`.`Orders` (
  `idOrders` INT NOT NULL AUTO_INCREMENT,
  `custumers_id` VARCHAR(45) NULL,
  `table_number` VARCHAR(45) NULL,
  `employee_id` INT NULL,
  `total_cost` VARCHAR(45) NULL,
  `orde_time` TIME NULL,
  PRIMARY KEY (`idOrders`),
  INDEX `customer_idx` (`custumers_id` ASC) VISIBLE,
  INDEX `emp_idx` (`employee_id` ASC) VISIBLE,
  CONSTRAINT `customer`
    FOREIGN KEY (`custumers_id`)
    REFERENCES `LittleLemonDB`.`CustomerDetails` (`first_name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `emp`
    FOREIGN KEY (`employee_id`)
    REFERENCES `LittleLemonDB`.`employees` (`idemployee`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `LittleLemonDB`.`Bills`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `LittleLemonDB`.`Bills` (
  `idorder_in_menu` INT NOT NULL,
  `item` VARCHAR(45) NOT NULL,
  `quantity` VARCHAR(45) NOT NULL,
  `Orders_idOrders` INT NOT NULL,
  `Menu_idMenu` INT NOT NULL,
  PRIMARY KEY (`Orders_idOrders`, `Menu_idMenu`),
  INDEX `fk_Bills_Orders1_idx` (`Orders_idOrders` ASC) INVISIBLE,
  INDEX `fk_Bills_Menu1_idx` (`Menu_idMenu` ASC) VISIBLE,
  CONSTRAINT `fk_Bills_Orders1`
    FOREIGN KEY (`Orders_idOrders`)
    REFERENCES `LittleLemonDB`.`Orders` (`idOrders`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Bills_Menu1`
    FOREIGN KEY (`Menu_idMenu`)
    REFERENCES `LittleLemonDB`.`Menu` (`idMenu`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `LittleLemonDB`.`order_state`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `LittleLemonDB`.`order_state` (
  `idorder_state` INT NOT NULL AUTO_INCREMENT,
  `state` VARCHAR(45) NULL,
  `ent_time` DATE NULL,
  `order_id` INT NULL,
  PRIMARY KEY (`idorder_state`),
  INDEX `order_idx` (`order_id` ASC) VISIBLE,
  CONSTRAINT `order`
    FOREIGN KEY (`order_id`)
    REFERENCES `LittleLemonDB`.`Orders` (`idOrders`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `LittleLemonDB`.`Booking`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `LittleLemonDB`.`Booking` (
  `idbooking` INT NOT NULL AUTO_INCREMENT,
  `emp_id` INT NULL,
  `customer_id` INT NULL,
  `booking_date` DATE NULL,
  `booking_time` DATE NULL,
  `booking_table` INT NOT NULL,
  `booking_state` VARCHAR(45) NULL,
  `is_deleted` TINYINT NULL,
  PRIMARY KEY (`idbooking`),
  INDEX `emp_idx` (`customer_id` ASC) VISIBLE,
  INDEX `emp_idx1` (`emp_id` ASC) VISIBLE,
  CONSTRAINT `cus`
    FOREIGN KEY (`customer_id`)
    REFERENCES `LittleLemonDB`.`CustomerDetails` (`idCustomer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `emp_booking`
    FOREIGN KEY (`emp_id`)
    REFERENCES `LittleLemonDB`.`employees` (`idemployee`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
